USE [cms]
GO

/****** Object:  Table [CMSWEB].[CODE_VALUE_T]    Script Date: 9/22/2016 10:07:24 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [CMSWEB].[CODE_VALUE_T](
	[OBJECTID] [numeric](18, 0) NOT NULL,
	[CODE] [nchar](50) NOT NULL,
	[CODE_GROUP] [nchar](50) NOT NULL,
	[SHORT_DESCRIPTION] [nchar](100) NOT NULL,
	[LONG_DESCRIPTION] [nchar](100) NULL,
	[EFFECTIVE_DATETIME] [datetime] NULL,
	[EFFECTIVE_THRU_DATETIME] [datetime] NULL,
	[ROW_CREATED_DATETIME] [datetime] NOT NULL,
	[ROW_CREATED_BY] [nchar](100) NOT NULL,
	[ROW_LAST_CHANGED_DATETIME] [datetime] NOT NULL,
	[ROW_LAST_CHANGED_BY] [nchar](100) NOT NULL
) ON [PRIMARY]

GO